//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.j2ee.pkgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Handles a user-provided generator.  You deploy any old generator
 *                 as a GBean, and then point to that GBean here.  The generator
 *                 should implement org.tranql.pkgenerator.PrimaryKeyGenerator.
 *             
 * 
 * <p>Java class for custom-generatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="custom-generatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="generator-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primary-key-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "custom-generatorType", propOrder = {
    "generatorName",
    "primaryKeyClass"
})
public class CustomGeneratorType {

    @XmlElement(name = "generator-name", required = true)
    protected String generatorName;
    @XmlElement(name = "primary-key-class", required = true)
    protected String primaryKeyClass;

    /**
     * Gets the value of the generatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratorName() {
        return generatorName;
    }

    /**
     * Sets the value of the generatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratorName(String value) {
        this.generatorName = value;
    }

    /**
     * Gets the value of the primaryKeyClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKeyClass() {
        return primaryKeyClass;
    }

    /**
     * Sets the value of the primaryKeyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKeyClass(String value) {
        this.primaryKeyClass = value;
    }

}
