//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.j2ee.pkgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *               Primary Key generation element.
 * 
 *               If this is present, a key generator GBean will be created
 *               and configured to generate IDs for the surrounding object.
 *             
 * 
 * <p>Java class for key-generatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="key-generatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="sequence-table" type="{http://www.openejb.org/xml/ns/pkgen-2.0}sequence-tableType"/>
 *         &lt;element name="auto-increment-table" type="{http://www.openejb.org/xml/ns/pkgen-2.0}auto-increment-tableType"/>
 *         &lt;element name="sql-generator" type="{http://www.openejb.org/xml/ns/pkgen-2.0}sql-generatorType"/>
 *         &lt;element name="custom-generator" type="{http://www.openejb.org/xml/ns/pkgen-2.0}custom-generatorType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "key-generatorType", propOrder = {
    "sequenceTable",
    "autoIncrementTable",
    "sqlGenerator",
    "customGenerator"
})
public class KeyGeneratorType {

    @XmlElement(name = "sequence-table")
    protected SequenceTableType sequenceTable;
    @XmlElement(name = "auto-increment-table")
    protected AutoIncrementTableType autoIncrementTable;
    @XmlElement(name = "sql-generator")
    protected SqlGeneratorType sqlGenerator;
    @XmlElement(name = "custom-generator")
    protected CustomGeneratorType customGenerator;

    /**
     * Gets the value of the sequenceTable property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceTableType }
     *     
     */
    public SequenceTableType getSequenceTable() {
        return sequenceTable;
    }

    /**
     * Sets the value of the sequenceTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceTableType }
     *     
     */
    public void setSequenceTable(SequenceTableType value) {
        this.sequenceTable = value;
    }

    /**
     * Gets the value of the autoIncrementTable property.
     * 
     * @return
     *     possible object is
     *     {@link AutoIncrementTableType }
     *     
     */
    public AutoIncrementTableType getAutoIncrementTable() {
        return autoIncrementTable;
    }

    /**
     * Sets the value of the autoIncrementTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoIncrementTableType }
     *     
     */
    public void setAutoIncrementTable(AutoIncrementTableType value) {
        this.autoIncrementTable = value;
    }

    /**
     * Gets the value of the sqlGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link SqlGeneratorType }
     *     
     */
    public SqlGeneratorType getSqlGenerator() {
        return sqlGenerator;
    }

    /**
     * Sets the value of the sqlGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlGeneratorType }
     *     
     */
    public void setSqlGenerator(SqlGeneratorType value) {
        this.sqlGenerator = value;
    }

    /**
     * Gets the value of the customGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link CustomGeneratorType }
     *     
     */
    public CustomGeneratorType getCustomGenerator() {
        return customGenerator;
    }

    /**
     * Sets the value of the customGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomGeneratorType }
     *     
     */
    public void setCustomGenerator(CustomGeneratorType value) {
        this.customGenerator = value;
    }

}
