//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.j2ee.pkgen;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openejb.xml.ns.pkgen_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KeyGenerator_QNAME = new QName("http://www.openejb.org/xml/ns/pkgen-2.0", "key-generator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openejb.xml.ns.pkgen_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatabaseGeneratedType }
     * 
     */
    public DatabaseGeneratedType createDatabaseGeneratedType() {
        return new DatabaseGeneratedType();
    }

    /**
     * Create an instance of {@link SqlGeneratorType }
     * 
     */
    public SqlGeneratorType createSqlGeneratorType() {
        return new SqlGeneratorType();
    }

    /**
     * Create an instance of {@link SequenceTableType }
     * 
     */
    public SequenceTableType createSequenceTableType() {
        return new SequenceTableType();
    }

    /**
     * Create an instance of {@link CustomGeneratorType }
     * 
     */
    public CustomGeneratorType createCustomGeneratorType() {
        return new CustomGeneratorType();
    }

    /**
     * Create an instance of {@link KeyGeneratorType }
     * 
     */
    public KeyGeneratorType createKeyGeneratorType() {
        return new KeyGeneratorType();
    }

    /**
     * Create an instance of {@link AutoIncrementTableType }
     * 
     */
    public AutoIncrementTableType createAutoIncrementTableType() {
        return new AutoIncrementTableType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyGeneratorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openejb.org/xml/ns/pkgen-2.0", name = "key-generator")
    public JAXBElement<KeyGeneratorType> createKeyGenerator(KeyGeneratorType value) {
        return new JAXBElement<KeyGeneratorType>(_KeyGenerator_QNAME, KeyGeneratorType.class, null, value);
    }

}
