//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.j2ee.loginconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Defines the list of login modules for a login configuration represented by a GenericSecurityRealm
 *             
 * 
 * <p>Java class for login-configType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="login-configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="login-module-ref" type="{http://geronimo.apache.org/xml/ns/loginconfig-1.1}login-module-refType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="login-module" type="{http://geronimo.apache.org/xml/ns/loginconfig-1.1}login-moduleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "login-configType", propOrder = {
    "loginModuleRefOrLoginModule"
})
public class LoginConfigType {

    @XmlElements({
        @XmlElement(name = "login-module-ref", type = LoginModuleRefType.class),
        @XmlElement(name = "login-module", type = LoginModuleType.class)
    })
    protected List<AbstractLoginModuleType> loginModuleRefOrLoginModule;

    /**
     * Gets the value of the loginModuleRefOrLoginModule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loginModuleRefOrLoginModule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoginModuleRefOrLoginModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoginModuleRefType }
     * {@link LoginModuleType }
     * 
     * 
     */
    public List<AbstractLoginModuleType> getLoginModuleRefOrLoginModule() {
        if (loginModuleRefOrLoginModule == null) {
            loginModuleRefOrLoginModule = new ArrayList<AbstractLoginModuleType>();
        }
        return this.loginModuleRefOrLoginModule;
    }

}
