//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.openejb.xml.ns.openejb_jar_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openejb.xml.ns.openejb_jar_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OpenejbJar_QNAME = new QName("http://www.openejb.org/xml/ns/openejb-jar-2.1", "openejb-jar");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openejb.xml.ns.openejb_jar_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityBeanType.Cache }
     * 
     */
    public EntityBeanType.Cache createEntityBeanTypeCache() {
        return new EntityBeanType.Cache();
    }

    /**
     * Create an instance of {@link ActivationConfigType }
     * 
     */
    public ActivationConfigType createActivationConfigType() {
        return new ActivationConfigType();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     * 
     */
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link OpenejbJarType }
     * 
     */
    public OpenejbJarType createOpenejbJarType() {
        return new OpenejbJarType();
    }

    /**
     * Create an instance of {@link EjbRelationshipRoleType.RoleMapping }
     * 
     */
    public EjbRelationshipRoleType.RoleMapping createEjbRelationshipRoleTypeRoleMapping() {
        return new EjbRelationshipRoleType.RoleMapping();
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link EntityBeanType }
     * 
     */
    public EntityBeanType createEntityBeanType() {
        return new EntityBeanType();
    }

    /**
     * Create an instance of {@link ActivationConfigPropertyType }
     * 
     */
    public ActivationConfigPropertyType createActivationConfigPropertyType() {
        return new ActivationConfigPropertyType();
    }

    /**
     * Create an instance of {@link MessageDrivenBeanType }
     * 
     */
    public MessageDrivenBeanType createMessageDrivenBeanType() {
        return new MessageDrivenBeanType();
    }

    /**
     * Create an instance of {@link WebServiceSecurityType }
     * 
     */
    public WebServiceSecurityType createWebServiceSecurityType() {
        return new WebServiceSecurityType();
    }

    /**
     * Create an instance of {@link EjbRelationshipRoleType.RoleMapping.CmrFieldMapping }
     * 
     */
    public EjbRelationshipRoleType.RoleMapping.CmrFieldMapping createEjbRelationshipRoleTypeRoleMappingCmrFieldMapping() {
        return new EjbRelationshipRoleType.RoleMapping.CmrFieldMapping();
    }

    /**
     * Create an instance of {@link QueryType.QueryMethod.MethodParams }
     * 
     */
    public QueryType.QueryMethod.MethodParams createQueryTypeQueryMethodMethodParams() {
        return new QueryType.QueryMethod.MethodParams();
    }

    /**
     * Create an instance of {@link EjbRelationshipRoleType }
     * 
     */
    public EjbRelationshipRoleType createEjbRelationshipRoleType() {
        return new EjbRelationshipRoleType();
    }

    /**
     * Create an instance of {@link GroupType.CmrField }
     * 
     */
    public GroupType.CmrField createGroupTypeCmrField() {
        return new GroupType.CmrField();
    }

    /**
     * Create an instance of {@link EjbRelationType }
     * 
     */
    public EjbRelationType createEjbRelationType() {
        return new EjbRelationType();
    }

    /**
     * Create an instance of {@link QueryType.QueryMethod }
     * 
     */
    public QueryType.QueryMethod createQueryTypeQueryMethod() {
        return new QueryType.QueryMethod();
    }

    /**
     * Create an instance of {@link SessionBeanType }
     * 
     */
    public SessionBeanType createSessionBeanType() {
        return new SessionBeanType();
    }

    /**
     * Create an instance of {@link OpenejbJarType.EnterpriseBeans }
     * 
     */
    public OpenejbJarType.EnterpriseBeans createOpenejbJarTypeEnterpriseBeans() {
        return new OpenejbJarType.EnterpriseBeans();
    }

    /**
     * Create an instance of {@link CmpFieldGroupMappingType }
     * 
     */
    public CmpFieldGroupMappingType createCmpFieldGroupMappingType() {
        return new CmpFieldGroupMappingType();
    }

    /**
     * Create an instance of {@link EntityGroupMappingType }
     * 
     */
    public EntityGroupMappingType createEntityGroupMappingType() {
        return new EntityGroupMappingType();
    }

    /**
     * Create an instance of {@link TssType }
     * 
     */
    public TssType createTssType() {
        return new TssType();
    }

    /**
     * Create an instance of {@link EntityBeanType.CmpFieldMapping }
     * 
     */
    public EntityBeanType.CmpFieldMapping createEntityBeanTypeCmpFieldMapping() {
        return new EntityBeanType.CmpFieldMapping();
    }

    /**
     * Create an instance of {@link EjbRelationshipRoleType.CmrField }
     * 
     */
    public EjbRelationshipRoleType.CmrField createEjbRelationshipRoleTypeCmrField() {
        return new EjbRelationshipRoleType.CmrField();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link CmrFieldGroupMappingType }
     * 
     */
    public CmrFieldGroupMappingType createCmrFieldGroupMappingType() {
        return new CmrFieldGroupMappingType();
    }

    /**
     * Create an instance of {@link EntityBeanType.PrefetchGroup }
     * 
     */
    public EntityBeanType.PrefetchGroup createEntityBeanTypePrefetchGroup() {
        return new EntityBeanType.PrefetchGroup();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link EjbRelationshipRoleType.RelationshipRoleSource }
     * 
     */
    public EjbRelationshipRoleType.RelationshipRoleSource createEjbRelationshipRoleTypeRelationshipRoleSource() {
        return new EjbRelationshipRoleType.RelationshipRoleSource();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenejbJarType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openejb.org/xml/ns/openejb-jar-2.1", name = "openejb-jar")
    public JAXBElement<OpenejbJarType> createOpenejbJar(OpenejbJarType value) {
        return new JAXBElement<OpenejbJarType>(_OpenejbJar_QNAME, OpenejbJarType.class, null, value);
    }

}
