//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.j2ee.connector;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for partitionedpoolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="partitionedpoolType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}singlepoolType">
 *       &lt;sequence>
 *         &lt;element name="partition-by-subject" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}emptyType" minOccurs="0"/>
 *         &lt;element name="partition-by-connectionrequestinfo" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}emptyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "partitionedpoolType", propOrder = {
    "partitionBySubject",
    "partitionByConnectionrequestinfo"
})
public class PartitionedpoolType
    extends SinglepoolType
{

    @XmlElement(name = "partition-by-subject")
    protected EmptyType partitionBySubject;
    @XmlElement(name = "partition-by-connectionrequestinfo")
    protected EmptyType partitionByConnectionrequestinfo;

    /**
     * Gets the value of the partitionBySubject property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType }
     *     
     */
    public EmptyType getPartitionBySubject() {
        return partitionBySubject;
    }

    /**
     * Sets the value of the partitionBySubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType }
     *     
     */
    public void setPartitionBySubject(EmptyType value) {
        this.partitionBySubject = value;
    }

    /**
     * Gets the value of the partitionByConnectionrequestinfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType }
     *     
     */
    public EmptyType getPartitionByConnectionrequestinfo() {
        return partitionByConnectionrequestinfo;
    }

    /**
     * Sets the value of the partitionByConnectionrequestinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType }
     *     
     */
    public void setPartitionByConnectionrequestinfo(EmptyType value) {
        this.partitionByConnectionrequestinfo = value;
    }

}
