//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.xml.ns.j2ee.connector_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 reference back into standard dd
 *             
 * 
 * <p>Java class for adminobjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminobjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adminobject-interface" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}fully-qualified-classType"/>
 *         &lt;element name="adminobject-class" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}fully-qualified-classType"/>
 *         &lt;element name="adminobject-instance" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}adminobject-instanceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminobjectType", propOrder = {
    "adminobjectInterface",
    "adminobjectClass",
    "adminobjectInstance"
})
public class AdminobjectType {

    @XmlElement(name = "adminobject-interface", required = true)
    protected String adminobjectInterface;
    @XmlElement(name = "adminobject-class", required = true)
    protected String adminobjectClass;
    @XmlElement(name = "adminobject-instance")
    protected List<AdminobjectInstanceType> adminobjectInstance;

    /**
     * Gets the value of the adminobjectInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminobjectInterface() {
        return adminobjectInterface;
    }

    /**
     * Sets the value of the adminobjectInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminobjectInterface(String value) {
        this.adminobjectInterface = value;
    }

    /**
     * Gets the value of the adminobjectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminobjectClass() {
        return adminobjectClass;
    }

    /**
     * Sets the value of the adminobjectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminobjectClass(String value) {
        this.adminobjectClass = value;
    }

    /**
     * Gets the value of the adminobjectInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adminobjectInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdminobjectInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminobjectInstanceType }
     * 
     * 
     */
    public List<AdminobjectInstanceType> getAdminobjectInstance() {
        if (adminobjectInstance == null) {
            adminobjectInstance = new ArrayList<AdminobjectInstanceType>();
        }
        return this.adminobjectInstance;
    }

}
