//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.17 at 01:03:24 AM CST 
//


package org.apache.geronimo.xml.ns.j2ee.connector_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceadapterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceadapterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceadapter-instance" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}resourceadapter-instanceType" minOccurs="0"/>
 *         &lt;element name="outbound-resourceadapter" type="{http://geronimo.apache.org/xml/ns/j2ee/connector-1.1}outbound-resourceadapterType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceadapterType", propOrder = {
    "resourceadapterInstance",
    "outboundResourceadapter"
})
public class ResourceadapterType {

    @XmlElement(name = "resourceadapter-instance")
    protected ResourceadapterInstanceType resourceadapterInstance;
    @XmlElement(name = "outbound-resourceadapter")
    protected OutboundResourceadapterType outboundResourceadapter;

    /**
     * Gets the value of the resourceadapterInstance property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceadapterInstanceType }
     *     
     */
    public ResourceadapterInstanceType getResourceadapterInstance() {
        return resourceadapterInstance;
    }

    /**
     * Sets the value of the resourceadapterInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceadapterInstanceType }
     *     
     */
    public void setResourceadapterInstance(ResourceadapterInstanceType value) {
        this.resourceadapterInstance = value;
    }

    /**
     * Gets the value of the outboundResourceadapter property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundResourceadapterType }
     *     
     */
    public OutboundResourceadapterType getOutboundResourceadapter() {
        return outboundResourceadapter;
    }

    /**
     * Sets the value of the outboundResourceadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundResourceadapterType }
     *     
     */
    public void setOutboundResourceadapter(OutboundResourceadapterType value) {
        this.outboundResourceadapter = value;
    }

}
