//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.29 at 06:48:36 PM IST 
//


package org.apache.geronimo.jee.loginconfig;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abstract-login-moduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstract-login-moduleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="control-flag" use="required" type="{http://geronimo.apache.org/xml/ns/loginconfig-2.0}control-flagType" />
 *       &lt;attribute name="wrap-principals" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstract-login-moduleType")
public abstract class AbstractLoginModule implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlAttribute(name = "control-flag", required = true)
    protected ControlFlag controlFlag;
    @XmlAttribute(name = "wrap-principals")
    protected Boolean wrapPrincipals;

    /**
     * Gets the value of the controlFlag property.
     * 
     * @return
     *     possible object is
     *     {@link ControlFlag }
     *     
     */
    public ControlFlag getControlFlag() {
        return controlFlag;
    }

    /**
     * Sets the value of the controlFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlFlag }
     *     
     */
    public void setControlFlag(ControlFlag value) {
        this.controlFlag = value;
    }

    /**
     * Gets the value of the wrapPrincipals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWrapPrincipals() {
        return wrapPrincipals;
    }

    /**
     * Sets the value of the wrapPrincipals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWrapPrincipals(Boolean value) {
        this.wrapPrincipals = value;
    }

}
