//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.29 at 06:48:36 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geronimo.apache.org/xml/ns/loginconfig-2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.apache.geronimo.jee.loginconfig;
